---
title: "Membership"
---

We welcome new members at all times. Members are the beating heart of our community and becoming a member is a way of supporting the club.

Members enjoy unlimited access to our weekly Friday sessions for the rest of the membership year. The membership year runs from the 1st of September until the 31st of August each year, regardless of when you become a member. For anyone attending our sessions semi-regularly, it is cheaper to become a member than to pay the £6 on-the-door fee.

The membership fee depends on the time of year that you decide to become a member, as per the table below.

| Month you become a member  | Membership fee (for all sessions until 31 August) |
| -------- | ------- |
| September-November  | £200 |
| December-February  | £160 |
| March-May  | £120 |
| June-August  | £80 |

We accept card payment and bank transfers. Please attend one of our sessions for a card payment or inquire for bank details.

The club is committed to making its activities accessible to everyone in the community. We recognise that financial hardship can be a barrier to participation, and we are committed to offering support to individuals and families who are experiencing financial difficulties. This policy sets out the principles and process for accessing free or subsidised services for those facing financial hardship or living on a low income: [Financial hardship policy](https://drive.google.com/file/d/1j7kxfWGU05WcrsIlVSeomTLbnt1OHwNj/view?usp=sharing).

Any questions about membership? Please [contact us](contact.qmd).
