---
title: "Play"
---

Our weekly sessions are designed to be inclusive of everyone, whether playing leisurely or competitively. Our coach is available to provide advice.

We normally play on a Friday evenings. We break for half term but we play over the summer. There may be other small variations due to the varying availability of the hall. Please see the table below for the detail. Join the club's WhatsApp group (see the "contact us" page) for regular reminders.

We are open to all adults and motivated, supervised children aged 12 and over. New joiners are welcome to simply turn up at the session of their choice. We can supply all the equipment required, including lending bats. If you have a question before joining, please see the "contact us" page.

| Date | Venue | Time | To note |
| -------- | -------- | -------- | -------- |
| Friday 25 July 2025 | Sports Hall | 6-7.30pm |
| Friday 1 August 2025 | Sports Hall | 6-7.30pm | No coaching |
| ~~Friday 8 August 2025~~ | ~~Sports Hall~~ | ~~6-7.30pm~~ | CANCELLED |
| Friday 15 August 2025 | Sports Hall | 6-7.30pm |
| Friday 22 August 2025 | Sports Hall | 6-7.30pm |
| Friday 29 August 2025 | Sports Hall | 6-7.30pm |

End of the 2024-25 season and start of the 2025-26 season.

| Date | Venue | Time | To note |
| -------- | -------- | -------- | -------- |
| Friday 5 September 2025 | Sports Hall | 5.30-6.45pm |
| Friday 12 September 2025 | Sports Hall | 5.30-6.45pm |
| Friday 19 September 2025 | Sports Hall | 5.30-6.45pm |
| Friday 26 September 2025 | Sports Hall | 5.30-6.45pm |
| Friday 3 October 2025 | Sports Hall | 5.30-6.45pm |
| Friday 10 October 2025 | Sports Hall | 5.30-6.45pm |
| Friday 17 October 2025 | Sports Hall | 5.30-6.45pm |
| Friday 24 October 2025 | Sports Hall | 5.30-6.45pm |

One-week break.

| Date | Venue | Time | To note |
| Friday 7 November 2025 | Sports Hall | 5.30-6.45pm |
| Friday 14 November 2025 | Sports Hall | 5.30-6.45pm |
| Friday 21 November 2025 | Sports Hall | 5.30-6.45pm |
| Friday 28 November 2025 | Sports Hall | 5.30-6.45pm |
| Friday 5 December 2025 | Sports Hall | 5.30-6.45pm |
| Friday 12 December 2025 | Sports Hall | 5.30-6.45pm |
| Friday 19 December 2025 | Sports Hall | 5.30-6.45pm |

Christmas break. Dates for 2026, starting from Friday 9 January 2026, will be announced in due course.

There are two ways to join us:

| Non-members  | Become a member |
| -------- | ------- |
| £6 on the door  | Unlimited access until the end of the season (31 August every year), price for 2025-26 to be announced shortly |
| Card, cash, or bank transfer | Card or bank transfer |

If you are intending to come regularly, please fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSeElvgpaoJbczteYr2RKx2OMc3yo-FwpwUwaxU0pzclbHrW2A/viewform?usp=sf_link).

We are also hoping to hold larger events for the community. To be notified, check options on the contact us page.
